### ISSUE TITLE
Stop the scrollableness left and right on the display

### ISSUE THREAD

**Issue by VagishVela** [Perceptive-Porcupines/Perceptive-Porcupines-Code-Jam-8#42]
Maybe split the text to max 79 chars or something?

**Comment by mustafaquraish** [comment]
I don't think manually splitting the text to a certain width is the right move here. There's definitely a way to get textual to wrap it manually. That's what happened before the newest update, so I guess someone just needs to go look at what changed in the ScrollView that disabled the automatic wrapping and how we can enable it again.

**Comment by mustafaquraish** [comment]
Turns out this is because of a hack made in `textual` for debugging purposes by the author that was left in the main code base. We probably need to wait for it to be updated (or create our own fork for now and fix it)

https://github.com/willmcgugan/textual/commit/fccdcaad2efb42ce93d289e76cd46a95149e74a0#r53447098

**Comment by briancohan** [comment]
Seems like the code has been fixed, though he hasn't published a new release. We could try to patch the method ourselves, install from the current commit, or hope he issues a new release soon.

**Comment by briancohan** [comment]
That's what I meant by "install from the current commit" I forget the exact syntax, but you can install from a github commit rather than pypi
